module.exports = {
  'Canada': { code: 'CAN', iso: 'ca' },
  'Mexico': { code: 'MEX', iso: 'mx' },
  'United States': { code: 'USA', iso: 'us' },
  'Algeria': { code: 'ALG', iso: 'dz' },
  'Cabo Verde': { code: 'CPV', iso: 'cv' },
  'Congo DR': { code: 'COD', iso: 'cd' },
  'Côte d\'Ivoire': { code: 'CIV', iso: 'ci' },
  'Egypt': { code: 'EGY', iso: 'eg' },
  'Ghana': { code: 'GHA', iso: 'gh' },
  'Morocco': { code: 'MAR', iso: 'ma' },
  'Senegal': { code: 'SEN', iso: 'sn' },
  'South Africa': { code: 'RSA', iso: 'za' },
  'Tunisia': { code: 'TUN', iso: 'tn' },
  'Australia': { code: 'AUS', iso: 'au' },
  'IR Iran': { code: 'IRN', iso: 'ir' },
  'Iraq': { code: 'IRQ', iso: 'iq' },
  'Japan': { code: 'JPN', iso: 'jp' },
  'Jordan': { code: 'JOR', iso: 'jo' },
  'Korea Republic': { code: 'KOR', iso: 'kr' },
  'Qatar': { code: 'QAT', iso: 'qa' },
  'Saudi Arabia': { code: 'KSA', iso: 'sa' },
  'Uzbekistan': { code: 'UZB', iso: 'uz' },
  'Austria': { code: 'AUT', iso: 'at' },
  'Belgium': { code: 'BEL', iso: 'be' },
  'Bosnia and Herzegovina': { code: 'BIH', iso: 'ba' },
  'Croatia': { code: 'CRO', iso: 'hr' },
  'Czechia': { code: 'CZE', iso: 'cz' },
  'England': { code: 'ENG', iso: 'gb-eng' },
  'France': { code: 'FRA', iso: 'fr' },
  'Germany': { code: 'GER', iso: 'de' },
  'Netherlands': { code: 'NED', iso: 'nl' },
  'Norway': { code: 'NOR', iso: 'no' },
  'Portugal': { code: 'POR', iso: 'pt' },
  'Scotland': { code: 'SCO', iso: 'gb-sct' },
  'Spain': { code: 'ESP', iso: 'es' },
  'Sweden': { code: 'SWE', iso: 'se' },
  'Switzerland': { code: 'SUI', iso: 'ch' },
  'Türkiye': { code: 'TUR', iso: 'tr' },
  'Curaçao': { code: 'CUW', iso: 'cw' },
  'Haiti': { code: 'HAI', iso: 'ht' },
  'Panama': { code: 'PAN', iso: 'pa' },
  'New Zealand': { code: 'NZL', iso: 'nz' },
  'Argentina': { code: 'ARG', iso: 'ar' },
  'Brazil': { code: 'BRA', iso: 'br' },
  'Colombia': { code: 'COL', iso: 'co' },
  'Ecuador': { code: 'ECU', iso: 'ec' },
  'Paraguay': { code: 'PAR', iso: 'py' },
  'Uruguay': { code: 'URU', iso: 'uy' }
};
